[package]
name = "customrgb"
version = "0.1.0"
edition = "2024"

[dependencies]
openrgb2 = "0.3.0"
phf = { version="0.13.1", features=["macros"]}
serde = { version="1.0.228", features=["derive"]}
serde_yaml = "0.9.34"
tokio = { version="1.47.1", features=["full"] }
